[package]
name = "moray"
version = "0.1.0"
authors = ["Anthony H <anthony@hevia.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
clap = "2.33.3"